import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

public class Formatter {

	public static void main(String[] args) throws FileNotFoundException, IOException {
		// takes some .csv file generated by dinning hall aggregate software 
		Scanner scan = new Scanner(new File("C:/Users/Cx831/Desktop/a.csv"));
		PrintWriter write = new PrintWriter("C:/Users/Cx831/Desktop/b.csv");
		
		// initializing global variables
		String line = scan.nextLine();
		String[] date = null;
		
		// traversing file
		while (scan.hasNext()) {
			line = scan.nextLine();
			
			// line disambiguators
			if (line.contains("day,")) { 
				// lines containing days of week; e.g. Monday...
				date = line.split(",");
				System.out.println ("splitted " + date[1]);
				
			} else if (line.contains("Day")) {
				// lines containing Day; i.e. Day totals
				line = date[0].substring(1) + "," + date[1].substring(0, date[1].length() - 1) + ",0, " + line;
				write.println(line);
			} else if (line.startsWith("Start")) {
				// first line
			} else {
				// lines of actual entries
				String fDay = date[0].substring(1);
				String fDate = date[1].substring(0, date[1].length() - 1);
				
				line = fDay + "," + fDate + "," + line;
				write.println(line);
				//Debug System.out.println ("added" + date[1]);
			}
		}

	}

}
