import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

public class SplitDay {

	public static void main(String[] args) throws FileNotFoundException, IOException {
		// takes some .csv file generated by dinning hall aggregate software 
		Scanner scan = new Scanner(new File(args[0]));
		PrintWriter write = new PrintWriter(args[1]);
	
		// initializing global variables

		// traversing file
		while (scan.hasNext()) {
			write.flush();
			String input = scan.nextLine();
			String[] line = input.split(",");
			String output = input;

			// mm/dd/yy
			if (line.length >= 7){
				String date[] = line[2].split("/");
				output = line[0] + "," + line[1] + "," + date[0] + "," + date[1] + "," + date[2] + "," + line[3] + "," + line[6] + "," + line[7];
	 
			}
			write.println(output);
			
		}

	}

}
